config/routes.rb
Rails.application.routes.draw do
  resources :leaderships
  resources :ministeries
  	get 'ministeries/:id/team' , to: 'ministeries#team'
  	
  resources :events
  resources :people
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :users, optional: true

  mount_uploader :image, ImageUploader


  after_create :save_user


  TYPE_LEADER = [ "Jovenes", "Adultos"]
  LEVEL = [ "12", "144", "1728"]

  scope :disciples, ->{ where('id <> ?', 1)}
  scope :leader12, ->{ where('level_leader = ?', '12')}

  def codigo_aleatorio
    caracter = %w{ A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 
                   a b c d e f g h i j k l m n o p q r s t u v w x y z
                   0 1 2 3 4 5 6 7 8 9 }
    posicion = rand(caracter.length)

    return caracter[posicion]
  end

  def generar_password
    aleatorio = ''
    6.times do
      aleatorio << codigo_aleatorio
    end
    password = aleatorio
    return password
  end

  def save_user
    user = User.new
    user.email = self.email
    if self.email == "admin@admin.com"
      user.password = "Admin1"
    else
      password_generated = generar_password
      user.password = password_generated
    end
    user.save
    update(users_id: user.id, password: password_generated)
  end

  def complete_name
    "#{self.name} #{self.surname}"
  end


end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    if current_user.id == 1
      @people = Person.disciples
    else
      @people = Person.where(leader: current_user.id)
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    @leader = Person.where("id <> ?", 1).order("id DESC")
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(
        :identification, 
        :name, :surname, 
        :date_birth, 
        :direction, 
        :email, 
        :phone, 
        :users_id,
        :leader,
        :type_leader,
        :level_leader,
        :is_admin,
        :image)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Identificacion %>
    <%= form.text_field :identification %>
  </div>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Apellido %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :Fecha_de_Nacimiento %>
    <%= form.text_field :date_birth %>
  </div>

  <div class="field">
    <%= form.label :Direccion %>
    <%= form.text_area :direction %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :Telefono %>
    <%= form.text_field :phone %>
  </div>

  <% if current_user.id == 1%>
    <div class="field">
      <%= form.label :Lider %>
      <%= form.collection_select :leader, Person.where("id <> ?", 1), :id, :complete_name, validate: true,:prompt=>"Seleccione"  %>

    </div>

    <div class="field">
      <%= form.label :Servicio %>
      <%= form.select :type_leader, Person::TYPE_LEADER, include_blank:"Seleccione" %>

    </div>

    <div class="field">
      <%= form.label :Nivel %>
      <%= form.select :level_leader, Person::LEVEL, include_blank:"Seleccione" %>
    </div>

    <div class="field">
      <%= form.label :Es_Administrador %>
      <%= form.check_box :is_admin %>
    </div>
  <%else%>
      <%= form.hidden_field :leader, value: current_user.id %>
  <%end%>
    <div>
      <%= form.label :Imagen %>
      <%= form.file_field :image %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<% if current_user.id == 1%>
  <h1>Editar Lider</h1>
<% else %>
  <h1>Editar Discipulo</h1>
<% end %>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.id == 1%>
  <h1>Lideres</h1>
<% else %>
  <h1>Mis Discipulos</h1>
<% end %>

<div style="float: right;">
  <%= link_to 'Agregar', new_person_path %>
</div>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Identification</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Date birth</th>
      <th>Direction</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td style="text-align: center;">
          <% if person.image.present? %>
            <%= image_tag(person.image_url, class:'rounded_avatar', :width => 30, :height => 30) %>
          <%else%>
            <%= image_tag('/usuario.png', class:'rounded_avatar', :width => 30, :height => 30) %>
          <%end%>
        </td>
        <td><%= person.identification %></td>
        <td><%= person.name.titleize %></td>
        <td><%= person.surname.titleize %></td>
        <td><%= person.date_birth %></td>
        <td><%= person.direction %></td>
        <td><%= person.email %></td>
        <td><%= person.phone %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<% if current_user.id == 1%>
  <h1>Nuevo Lider</h1>
<% else %>
  <h1>Nuevo Discipulo</h1>
<% end %>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identification:</strong>
  <%= @person.identification %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @person.surname %>
</p>

<p>
  <strong>Date birth:</strong>
  <%= @person.date_birth %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @person.direction %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>