config/routes.rb
Rails.application.routes.draw do
  resources :leaderships
  resources :ministeries
  	get 'ministeries/:id/team' , to: 'ministeries#team'
  	
  resources :events
  resources :people
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/leadership.rb
class Leadership < ApplicationRecord
  has_many :leaders
  accepts_nested_attributes_for :leaders, allow_destroy: true

end

app/controllers/leaderships_controller.rb
class LeadershipsController < ApplicationController
  before_action :set_leadership, only: [:show, :edit, :update, :destroy]

  # GET /leaderships
  # GET /leaderships.json
  def index
    @leaderships = Leadership.all
  end

  # GET /leaderships/1
  # GET /leaderships/1.json
  def show
  end

  # GET /leaderships/new
  def new
    @leadership = Leadership.new
    2.times { @leadership.leaders.build }

  end

  # GET /leaderships/1/edit
  def edit
  end

  # POST /leaderships
  # POST /leaderships.json
  def create
    @leadership = Leadership.new(leadership_params)

    respond_to do |format|
      if @leadership.save
        format.html { redirect_to @leadership, notice: 'Leadership was successfully created.' }
        format.json { render :show, status: :created, location: @leadership }
      else
        format.html { render :new }
        format.json { render json: @leadership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderships/1
  # PATCH/PUT /leaderships/1.json
  def update
    respond_to do |format|
      if @leadership.update(leadership_params)
        format.html { redirect_to @leadership, notice: 'Leadership was successfully updated.' }
        format.json { render :show, status: :ok, location: @leadership }
      else
        format.html { render :edit }
        format.json { render json: @leadership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderships/1
  # DELETE /leaderships/1.json
  def destroy
    @leadership.destroy
    respond_to do |format|
      format.html { redirect_to leaderships_url, notice: 'Leadership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leadership
      @leadership = Leadership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leadership_params
      params.require(:leadership).permit(
                                  :name, :status, leaders_attributes: [
                                  :id, :person, :_destroy
                                  ])
    end
end

app/helpers/leaderships_helper.rb
module LeadershipsHelper
end

app/views/leaderships/_form.html.erb
<%= nested_form_for(@leadership, local: true) do |form| %>
  <% if leadership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leadership.errors.count, "error") %> prohibited this leadership from being saved:</h2>

      <ul>
      <% leadership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <fieldset id="leaders">
    <%= form.fields_for :leaders do |leaders_form| %>
      <div class="field">
        <%= leaders_form.label :person, 'Nombre de lider' %><br>
        <%= leaders_form.text_field :person %>
        <%= leaders_form.collection_select :person, Person.where("id <> ?", 1).leader12, :id, :complete_name, validate: true,:prompt=>"Seleccione"  %>
      </div>
          
    <% end %>
  </fieldset>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leaderships/edit.html.erb
<h1>Editing Leadership</h1>

<%= render 'form', leadership: @leadership %>

<%= link_to 'Show', @leadership %> |
<%= link_to 'Back', leaderships_path %>

app/views/leaderships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaderships.each do |leadership| %>
      <tr>
        <td><%= leadership.name %></td>
        <td><%= leadership.status %></td>
        <td><%= link_to 'Show', leadership %></td>
        <td><%= link_to 'Edit', edit_leadership_path(leadership) %></td>
        <td><%= link_to 'Destroy', leadership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leadership', new_leadership_path %>

app/views/leaderships/new.html.erb
<h1>New Leadership</h1>

<%= render 'form', leadership: @leadership %>

<%= link_to 'Back', leaderships_path %>

app/views/leaderships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leadership.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @leadership.status %>
</p>

<%= link_to 'Edit', edit_leadership_path(@leadership) %> |
<%= link_to 'Back', leaderships_path %>